### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by t4sk** [sdhnt/ls.app#1]
## Sign up (completed)
- [x] 1. Power Ranger uses application to sign up users. (Note: I think initially the User ID should just be the
phone number)

- [x] @t4sk find user by mobile

- [x] 2. At the end of the Signup process users get a text message to welcome them to LiquidStar and asks them to enter a 4 digit pin number. (User is added to database)

- [x] @t4sk send Twilio to user on sign up
- [x] @t4sk user sends pin to Twilio and user's account is activated

## Rent battery (WIP @t4sk)
- [x] 3. User approaches power ranger to rent battery.

- [x] 4. User gives power ranger information so power ranger can pull up their account (phone number or name to start).

- [ ] 5. Power ranger use application to do facial recognition match (threshold above 70%). Note : On this screen the picture in the account needs to show up to do a side by side.

@sdhnt UI for facial recognition

- [ ] 6. If match power ranger sees screen to enter what battery size rental wanted 10K or 20K and how many days rental. Then they see a screen that tells them to ask for $X in cash (Deposit + # of Days Rental X Rental Cost per Day)

@sdhnt UI to fill battery rental (first write balance to /accounts collection, then the rental request to /batteryRentals)

- [x] @t4sk backend for accounting

- [ ] 7. If not a match app stores photograph and screen shows a picture of the ID provided (Power Ranger asks to see ID) and if match hits ok for next screen.

@sdhnt UI for facial recognition

@sdhnt store images to backend

- [ ] 8. Power Ranger does a QR Code scan of battery (QR Code needs to be tied to a 5 digit number also printed on the battery).

@sdhnt UI for QR code reader

- [x] 9. Power Ranger hands battery to customer. Customer enters battery number and ownership of battery is transferred from PR to customer.

- [x] 10. User receives text to confirm transfer to accept transfer the user input their pin number. In the text the battery number is included (i.e. Do you accept receipt of battery 12345? If yes enter pin 4 digit pin number to confirm... if no Power Ranger can just exit the process)

- [x] @t4sk twilio - customer sends / confirms rental
- [x] @t4sk Twilio to rent battery

## Return battery
- [ ] 11. User returns the battery and user gives power ranger information so power ranger can pull up their account (phone number or name to start).

@sdhnt UI to display user info

- [x] @t4sk backend for user info / account

- [ ] 12. Power ranger use application to do facial recognition match (threshold above 70%). Note : On this screen the picture in the account needs to show up to do a side by side.

@sdhnt UI for facial recognition
- [ ] 13. If match power ranger moves to screen that has QR code scanner of battery and scans battery. If battery matches User receives text that says thank you for renting a liquid star battery, user is asked if they want their deposit back (answer should be no if they are swapping for a charged up battery).

@sdhnt UI to scan QR code.
- [x] @t4sk Twilio message for checked out battery

- [ ] 14. If not a match app stores photograph and screen shows a picture of the ID provided (Power Ranger asks to see ID) and if match hits ok for QR screen.

@sdhnt store images to backend

- [ ] 15. If battery is not a match power ranger can see who's battery it is.
Admin

- [ ] 16. Power ranger needs an admin screen to see all batteries and who currently has them rented out, deposit amount, and number of days rented. If battery is late for return. Power Ranger can hit a button to send a reminder text and show amount owed.

- [x] @t4sk API to query battery rental
- [x] @t4sk twilio message to show amount owned

**Comment by sidhant** [comment]
You have the wrong sidhant tagged.

**Comment by t4sk** [comment]
@sidhant oops sorry :). Will fix
